name: Notify Google Chat on Push

on:
  push:
    branches:
      - main  # You can change this to match your active branch

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit details
        id: get_commit
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:%an)" >> $GITHUB_ENV
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Send commit to Google Chat
        run: |
          curl -X POST "${{ secrets.GOOGLE_CHAT_WEBHOOK }}" \
          -H 'Content-Type: application/json' \
          -d '{
                "text": "🚀 *New Commit to vr2_website*:\n*Author:* '"$COMMIT_AUTHOR"'\n*Message:* '"$COMMIT_MESSAGE"'\n🔗 *View Commit:* https://github.com/${{ github.repository }}/commit/'"$COMMIT_SHA"'"
              }'